### ISSUE TITLE
Slow loading scanner

### ISSUE THREAD

**Issue by aannuuj** [aslanyanhaik/RoundCode#1]
Please improve the loading and dismiss time of the scanner

**Comment by aslanyanhaik** [comment]
@aannuuj I'm working on that

**Comment by aslanyanhaik** [comment]
Hey @aannuuj just updated to version 1.1.0 which includes faster scanning logic

**Comment by aannuuj** [comment]
That’s great @aslanyanhaik 
Will update my pods
Would you like to connect in person?

**Comment by aslanyanhaik** [comment]
sure, you can message me on twitter. I'm always available.

**Comment by aannuuj** [comment]
Sure mate 😄
