### ISSUE TITLE
Android Clone

### ISSUE THREAD

**Issue by ljs19923** [aslanyanhaik/RoundCode#12]
Hi, Do you know if one Android repo exists, like a clone of your project ?

I want to use your code for one project, but i need to have the same with the android app, only to read it

Thanks

**Comment by aslanyanhaik** [comment]
@JulienLevallois working on the Android version. Should be ready by end of this year

**Comment by mrousavy** [comment]
@aslanyanhaik Hey! Do you have any progress for the Android version? I'm planning on integrating RoundCode in my react native app which is cross-platform.. Might also publish a native UI module for react native which wraps the iOS and Android implementations, obviously giving you credit.

**Comment by nafis042** [comment]
Any update on android side?

**Comment by aaparth** [comment]
hi,

Is there any update for this library in the Android.
