### ISSUE TITLE
Does the detection have to be on a white BG?

### ISSUE THREAD

**Issue by naturalui** [aslanyanhaik/RoundCode#2]
Seems like it only works on the output generated image (White Background), not while on a black BG (using the example app). Could this be made configurable?

I tried to apply a `CIFilter(name: "CIColorInvert")` to the pixelBuffer with not much luck.

**Comment by aslanyanhaik** [comment]
Already started working on this. Will release update next week.

**Comment by naturalui** [comment]
Thats awesome, thanks for this awesome component.

**Comment by aslanyanhaik** [comment]
@naturalui just pushed version 1.1.1 which adds support for dark background. 
I've added color validation functionality because there can be cases when developers choose dark colors which makes detection almost impossible.

**Comment by naturalui** [comment]
@aslanyanhaik 

Should this work? I'm testing white code on black background, does not seem to detect (both with camera or image)

![Screenshot 2020-05-04 at 12 43 20 AM](https://user-images.githubusercontent.com/1953861/80945330-6fe84c00-8da0-11ea-98eb-de6f4c7cfd1e.jpeg)
