### ISSUE TITLE
Increase number of accepted characters in textfield input

### ISSUE THREAD

**Issue by EdwinJr13** [aslanyanhaik/RoundCode#9]
Hey, 

I would like to know if it possible to increase the number of input characters in the textfield where you put your string with the default configuration. I want to pass firebase UID but I can because they are too long.

Thanks.

**Comment by aslanyanhaik** [comment]
@EdwinJr13 how many characters in firebase UID? You can change the configuration to `uuidConfiguration` which should be enough for firebase

**Comment by EdwinJr13** [comment]
> @EdwinJr13 how many characters in firebase UID? You can change the configuration to `uuidConfiguration` which should be enough for firebase

My UIDs are between 30 characters and 55 because I use custom auth (JWT tokens). The `uuidConfiguration` is not long enough

**Comment by aslanyanhaik** [comment]
@EdwinJr13 you can fork and try to modify `Version` in `RCCoderConfiguration` to increase characters

**Comment by EdwinJr13** [comment]
It's a bit tricky I don't know how to 😅
